#!/bin/bash
# motif SessionStart hook — primes new Claude Code sessions with
# resume context AND installs Python deps so tests/linters can run
# in a fresh sandbox (Claude Code on the web / desktop App).
#
# Stdout is surfaced as additional context to the new session, so
# the journal tail + git state lets a fresh chat pick up where the
# previous one left off without the user re-pasting context.
#
# Designed to be safe to run every session start: idempotent,
# non-interactive, swallow non-fatal errors so a missing journal
# (first-time use) or an offline pip mirror doesn't block startup.

set -uo pipefail

# 1. Dependency install — only in the remote sandbox (web/App).
#    Local dev environments already have their own setup, no need
#    to re-run pip every session.
if [ "${CLAUDE_CODE_REMOTE:-}" = "true" ]; then
  if [ -f requirements.txt ]; then
    pip install --quiet -r requirements.txt 2>&1 | tail -3 >&2 || true
  fi
  # pytest isn't pinned in requirements.txt (runtime image doesn't
  # need it) but we want it available so the new session can run
  # tests without pip-installing first.
  pip install --quiet pytest 2>&1 | tail -3 >&2 || true
fi

# 2. Resume context printed to stdout — Claude reads this as part
#    of its initial system context.
echo "# motif session resume context"
echo
echo "_Generated by .claude/hooks/session-start.sh on session start._"
echo

# Branch + working tree
echo "## branch + working tree"
echo
echo "- branch: \`$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo 'unknown')\`"
short_status=$(git status --short 2>/dev/null || true)
if [ -n "$short_status" ]; then
  echo "- working tree NOT clean:"
  echo "\`\`\`"
  echo "$short_status"
  echo "\`\`\`"
else
  echo "- working tree: clean"
fi
echo

# Recent commits — origin tip vs local for at-a-glance drift.
echo "## last 15 commits on this branch"
echo
echo "\`\`\`"
git log --oneline -15 2>/dev/null || echo "(no git log available)"
echo "\`\`\`"
echo

# Latest pushed tag — useful to confirm what's deployed.
latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || true)
if [ -n "$latest_tag" ]; then
  echo "## latest tag: \`$latest_tag\`"
  echo
fi

# Session journal tail. The journal is the human-readable digest
# of WHY we made each change. Append-only: every meaningful chunk
# of work gets a dated entry. New sessions read the tail to learn
# where the last one left off.
if [ -f docs/SESSION_JOURNAL.md ]; then
  echo "## docs/SESSION_JOURNAL.md (last 250 lines)"
  echo
  tail -250 docs/SESSION_JOURNAL.md
  echo
else
  echo "## docs/SESSION_JOURNAL.md: not yet created"
  echo
  echo "_Add an entry at the end of each meaningful task_"
  echo "_(see CLAUDE.md \"Session journaling\" for the format)._"
  echo
fi

exit 0
